---
- name: Add Keys to hosts
  hosts: 0.0.0.0 # Replace with your target host ip address.
  tasks:
  - name: Install Key
    authorized_key: 
      user: target_host_user_name	
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

